/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bank;

import bank.BankSystem;
public class App {
    public static void main(String[] args) {
        BankSystem system = new BankSystem(); 
        system.run(); 
    }
}
